spring.application.name=currency-exchange-service
server.port=8000
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.cloud.aws.region.static=eu-north-1
spring.config.import=aws-secretsmanager:prod/currency-conversion/sonarqube2



